# -*- coding: utf-8 -*-
"""B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vt6bEZb8fwv14Dp83uCUPJjz-tT308kC
"""

import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

N=3 #меняем как нам нужно

#построение графа
G = nx.Graph()
center = 0
leaves = list(range(1, N+1))
for leaf in leaves:
    G.add_edge(center, leaf)

#рисуем граф
plt.figure(figsize=(3, 3))
pos = nx.spring_layout(G)
node_colors = ['yellow' if node == center else 'green' for node in G.nodes()]
nx.draw(G, pos,with_labels=True,node_color=node_colors,node_size=400,font_size=10,font_weight='bold',edge_color='gray',width=1)
plt.title("Сеть B", fontsize=12)
plt.axis('off')
plt.show()
print("\n")

#считаем центральность по собственному вектору
eigen_cent = nx.eigenvector_centrality(G)

total = sum(eigen_cent.values())
eigen_norm = {node: val/total for node, val in eigen_cent.items()}

#получаем матрицу смежности из графа
A = nx.to_numpy_array(G, nodelist=sorted(G.nodes()))

#вычисляем лямду
c = np.array([eigen_norm[node] for node in sorted(G.nodes())])
Ac = A.T @ c
lamda= Ac[0] / c[0]

print(f"λ = {lamda:.4f}")
for node in sorted(eigen_norm.keys()):
    print(f"с{node} = {eigen_norm[node]:.4f}")
print(f"Сумма = {sum(eigen_norm.values()):.4f}")
print("\n")

#расчет PageRank
alpha = 0.25  ##затухание №1

pagerank = nx.pagerank(G, alpha=alpha)
print(f"PageRank (α = {alpha}):")
for node in sorted(pagerank.keys()):
    print(f"с{node} = {pagerank[node]:.6f}")
print(f"Сумма = {sum(pagerank.values()):.6f}")
print("\n")

alpha = 0.50  #затухание №2
pagerank = nx.pagerank(G, alpha=alpha)
print(f"PageRank (α = {alpha}):")
for node in sorted(pagerank.keys()):
    print(f"с{node} = {pagerank[node]:.6f}")
print(f"Сумма = {sum(pagerank.values()):.6f}")
print("\n")

#посмотрим как изменится при увеличении α
alpha = 0.85  #затухание №3

pagerank = nx.pagerank(G, alpha=alpha)
print(f"PageRank (α = {alpha}):")
for node in sorted(pagerank.keys()):
    print(f"с{node} = {pagerank[node]:.6f}")
print(f"Сумма = {sum(pagerank.values()):.6f}")
print("\n")

print(f"Итог: с0 растет, с1-с{N} падают")
print("\n")

#Центральность Каца-Боначича (α = 0,5)
alpha = 0.5   #затухание
beta = 1.0    #коэффициент

katz = nx.katz_centrality(G, alpha=0.5, beta=1.0)
#так как он нормирует, то получаются не те значения, что и у нас, поэтому наши значения нужно пронормировать чтоб сравнить
print(f"Центральность Каца–Боначича (α = {alpha}, β = {beta}):")
for node in sorted(katz.keys()):
    print(f"c{node} = {katz[node]:.6f}")

print("Для N<4 в сети типа «звезда» однозначно определена центральность Каца-Боначича (α =0,5), если брать больше то выходит ошибка")