# -*- coding: utf-8 -*-
"""task_2_2.04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yIkCunTNcSDfKQYVd7XQan-hnTIcIJih
"""

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

np.random.seed(42)

#1
def create_sbm_graph(n_nodes=200, n_blocks=4, p_in=0.15, p_out=0.008):
    block_sizes=[n_nodes//n_blocks]*n_blocks
    block_sizes[-1]+=n_nodes-sum(block_sizes)
    prob_matrix=np.full((n_blocks, n_blocks), p_out)
    np.fill_diagonal(prob_matrix, p_in)
    G=nx.stochastic_block_model(block_sizes, prob_matrix, seed=42)
    G=nx.convert_node_labels_to_integers(G)
    return G

G=create_sbm_graph(n_nodes=200, n_blocks=4, p_in=0.15, p_out=0.008)
n=G.number_of_nodes()
A=np.zeros((n, n))
for i in range(n):
    neighbors=list(G.neighbors(i))
    if len(neighbors)>0:
        for j in neighbors:
            A[i, j]=1.0/len(neighbors)
    else:
        A[i, i]=1.0

#2
x0=np.random.uniform(0, 1, n)
print(f"\n Начальные мнения: min={x0.min():.3f}, max={x0.max():.3f}")

#3
x=x0.copy()
history_dg=[x.copy()]

for t in range(200):
    x_new=A@x
    history_dg.append(x_new.copy())
    if np.linalg.norm(x_new-x)<0.000001:
        break
    x=x_new

final_dg=history_dg[-1]
consensus_dg=np.allclose(final_dg, final_dg[0], rtol=0.00001)

print(f"   Итераций: {len(history_dg)-1}")
print(f"   Консенсус: {'ДА' if consensus_dg else 'НЕТ'}")

plt.figure(figsize=(8, 5))
plt.hist(final_dg, bins=20, alpha=0.7, color='blue', edgecolor='black')
plt.xlabel('Мнение')
plt.ylabel('Количество агентов')
plt.title('Модель Де Гроота: распределение финальных мнений')
plt.grid(True, alpha=0.3)
plt.show()

#4
d_values=[0.1, 0.2, 0.3, 0.5]
results=[]

fig,axes=plt.subplots(1, len(d_values), figsize=(16, 4))

for idx, d in enumerate(d_values):
    x = x0.copy()
    for t in range(200):
        x_new=np.zeros(n)
        for i in range(n):
            trusted=x[np.abs(x-x[i])<d]
            x_new[i]=np.mean(trusted) if len(trusted)>0 else x[i]
        if np.linalg.norm(x_new - x)<0.000001:
            break
        x=x_new

    final=x_new
    consensus=np.allclose(final, final[0], rtol=0.00001)
    n_clusters=len(np.unique(np.round(final, 5)))
    results.append({'d': d, 'clusters': n_clusters, 'consensus': consensus})

    print(f"   d={d}: итераций={t+1}, консенсус={consensus}, кластеров={n_clusters}")

    # Распределение финальных мнений для каждого d
    axes[idx].hist(final, bins=20, alpha=0.7, color='red', edgecolor='black')
    axes[idx].set_xlabel('Мнение')
    axes[idx].set_ylabel('Количество')
    axes[idx].set_title(f'd = {d}\nкластеров: {n_clusters}')
    axes[idx].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

#ВЫВОДЫ
print("СРАВНЕНИЕ МОДЕЛЕЙ")

print(f"{'Модель':<25} {'Консенсус':<12} {'Кластеров':<12}")
print("-" * 50)
print(f"{'Де Гроот':<25} {'Да' if consensus_dg else 'Нет':<12} {len(np.unique(np.round(final_dg, 5))):<12}")
for r in results:
    print(f"Огр доверие (d={r['d']}):{' ':<5} {'Да' if r['consensus'] else 'Нет':<12} {r['clusters']:<12}")

print("\nВЫВОДЫ:")
print("-" * 50)
print("""
1. Модель Де Гроота:
   - Агенты усредняют мнения всех соседей по графу
   - В SBM графе формируются кластеры, соответствующие блокам

2. Модель ограниченного доверия:
   - Агенты усредняют только "близкие" мнения (|x_i - x_j| < d)
   - d=0.1 много кластеров
   - d=0.2-0.3 несколько крупных кластеров
   - d=0.5+ почти консенсус

3. Различия:
   - Де Гроот: структура сети жёстко определяет влияния
   - Модель ограниченного доверия: текущие мнения определяют влияния
   - При больших d стремится к Де Грооту
""")