# -*- coding: utf-8 -*-
"""task_2_20.03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLbBmSsA-Le5msxDnw_CG0-xYyf8s4Ir
"""

import networkx as nx
import matplotlib.pyplot as plt
from collections import Counter
import numpy as np
from networkx.algorithms.community import greedy_modularity_communities
import random
import math

n=1000
p=0.01

def generate_er_graph(n, p):
    G=nx.Graph()
    G.add_nodes_from(range(n))
    for i in range(n-1):
        for j in range(i+1, n):
            x=random.random()
            if x<p:
                G.add_edge(i, j)
    return G

G_er=generate_er_graph(n, p)

print(f"\n1. Граф Эрдеша-Реньи G({n}, {p})")
print(f"Вершин: {G_er.number_of_nodes()}")
print(f"Ребер: {G_er.number_of_edges()}")

print("\n2. Характеристики графа")

#Распределение степеней
degrees=[d for n, d in G_er.degree()]
degree_counts=Counter(degrees)
print("Распределение степеней")
print(f"Минимальная степень: {min(degrees)}")
print(f"Максимальная степень: {max(degrees)}")
print("Вероятность того, что вершина имеет степень k")
c=(n-1)*p
for k in range(min(degrees), max(degrees)+1):
    prob=math.exp(-c)*(c**k)/math.factorial(k)
    print(f"P{k}: {prob:.6f}")

#Средняя степень вершины
print(f"\nСредняя степень (факт): {np.mean(degrees):.3f}")
print(f"Средняя степень (теория): {c:.3f}")

#Коэффициент кластеризации
clustering_er=nx.average_clustering(G_er)
print(f"\nКоэффициент кластеризации")
print(f"Значение: {clustering_er:.6f}")
print(f"Теоретическое (p): {p:.4f}")

#Гигантская компонента
components=list(nx.connected_components(G_er))
giant_size=len(max(components, key=len))
print(f"\nГигантская компонента")
print(f"Всего компонент: {len(components)}")
print(f"Размер гигантской: {giant_size} ({giant_size/n*100:.1f}%)")


#Средняя длина пути
if giant_size>1:
    giant = G_er.subgraph(max(components, key=len))
    avg_path=nx.average_shortest_path_length(giant)
    print(f"\nСредняя длина пути")
    print(f"В гигантской компоненте: {avg_path:.3f}")
    print(f"Теоретическая ln(n)/ln(c): {np.log(n)/np.log(np.mean(degrees)):.3f}")

# 3. Стохастическая блочная модель (СБМ)
print("\n3. Стохастическая блочная модель")
sizes=[500, 500]
p_in=0.8
p_out=0.01
block_matrix=[[p_in, p_out],[p_out, p_in]]
G_sbm=nx.stochastic_block_model(sizes, block_matrix, seed=42)
true_labels=[0]*500+[1]*500
print(f"Параметры: 2 сообщества по 500 вершин")
print(f"p_внутри = {p_in}, p_между = {p_out}")
print(f"Вершин: {G_sbm.number_of_nodes()}")
print(f"Ребер: {G_sbm.number_of_edges()}")

# Характеристики СБМ
degrees_sbm=[d for n, d in G_sbm.degree()]
clustering_sbm=nx.average_clustering(G_sbm)

print(f"\nХарактеристики СБМ:")
print(f"Средняя степень: {np.mean(degrees_sbm):.3f}")
print(f"Коэффициент кластеризации: {clustering_sbm:.6f}")

components_sbm=list(nx.connected_components(G_sbm))
giant_sbm=len(max(components_sbm, key=len))
print(f"Гигантская компонента: {giant_sbm} ({giant_sbm/n*100:.1f}%)")

#4. Сравнение и обнаружение сообществ
communities_er = list(greedy_modularity_communities(G_er))
modularity_er = nx.community.modularity(G_er, communities_er)
n_comm_er = len(communities_er)

communities_sbm = list(greedy_modularity_communities(G_sbm))
modularity_sbm = nx.community.modularity(G_sbm, communities_sbm)
n_comm_sbm = len(communities_sbm)

print("\nсравнение степеней")
print("er           сбм")
print(f"{np.mean(degrees):.2f}     {np.mean(degrees_sbm):.2f}")

print("\nкластеризация")
print("er           сбм")
print(f"{clustering_er:.6f}     {clustering_sbm:.6f}")

print("\nгигантская компонента (%)")
print("er           сбм")
print(f"{giant_size/n*100:.1f}    {giant_sbm/n*100:.1f}")

print("\nмодульность")
print("er           сбм")
print(f"{modularity_er:.4f}     {modularity_sbm:.4f}")

print("\nВЫВОДЫ")
print("""
1. Эрдеша-Реньи:
   - Средняя степень составляет ≈10, что совпадает с теоретическим значением с
   - Кластеризация ≈0.01 (очень низкая)
   - Гигантская компонента >99% вершин
   - Модульность низкая, сообществ нет

2. Стохастическая блочная модель:
   - Средняя степень значительно выше, так как плотность связей внутри сообществ высокая
   - Коэффициент кластеризации значительно выше, чем у ER графа
   - Гигантская компонента >99% вершин
   - Четкая структура из двух сообществ
   - Модульность высокая
   - Алгоритм успешно находит сообщества

3. Ключевое различие:
   - ER: случайный граф без структуры
   - СБМ: граф с явными сообществами
""")