# -*- coding: utf-8 -*-
"""task_26.03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13F9slsHAszNydj82qavyFzw5VsfZKAOJ
"""

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import random

np.random.seed(None)
random.seed(None)

#1
def create_sbm_graph(n_nodes=200, n_blocks=4, p_in=0.15, p_out=0.008):
    block_sizes=[n_nodes//n_blocks]*n_blocks
    block_sizes[-1]+=n_nodes-sum(block_sizes)
    prob_matrix=np.full((n_blocks, n_blocks), p_out)
    np.fill_diagonal(prob_matrix, p_in)
    G=nx.stochastic_block_model(block_sizes, prob_matrix, seed=42)
    G=nx.convert_node_labels_to_integers(G)
    return G

def activation_probabilities(G, base_prob=0.1, prob_variance=0.05):
    probabilities = {}
    for u, v in G.edges():
        prob=base_prob+np.random.uniform(-prob_variance, prob_variance)
        prob=np.clip(prob, 0.05, 0.3)
        probabilities[(u, v)]=prob
        probabilities[(v, u)]=prob
    return probabilities

def icm_single_run(G, probabilities, initial_active, max_steps=100):
    active=set(initial_active)
    newly_active=set(initial_active)
    history=[active.copy()]
    for step in range(max_steps):
        if not newly_active:
            break
        next_candidates = set()
        for u in newly_active:
            for v in G.neighbors(u):
                if v not in active:
                    if random.random()<probabilities.get((u, v), 0.1):
                        next_candidates.add(v)
        newly_active=next_candidates-active
        active.update(next_candidates)
        history.append(active.copy())
    return history

def icm_multiple_runs(G, probabilities, initial_active, n_runs=100):
    final_sizes=[]
    for run in range(n_runs):
        history=icm_single_run(G, probabilities, initial_active)
        final_sizes.append(len(history[-1]))
    avg_final_size=np.mean(final_sizes)
    std_final_size=np.std(final_sizes)
    return {
        'final_sizes': final_sizes,
        'avg_final_size': avg_final_size,
        'std_final_size': std_final_size
    }

def visualize_steps(G, history_sets):
    n_steps=len(history_sets)
    pos=nx.spring_layout(G, seed=42, k=0.3)

    for step_idx, active_set in enumerate(history_sets):
        plt.figure(figsize=(10, 8))
        node_colors=[]
        for node in G.nodes():
            if node in active_set:
                node_colors.append('red')
            else:
                node_colors.append('lightgray')

        nx.draw(G, pos, node_color=node_colors,
                node_size=100, edge_color='gray', alpha=0.7,
                with_labels=False)

        plt.title(f'ШАГ {step_idx} - Активно: {len(active_set)} узлов', fontsize=14)
        plt.axis('off')

    return n_steps

#2
def estimate_influence(G, probabilities, S, n_runs=100):
    if len(S)==0:
        return 0
    total_active=0
    for _ in range(n_runs):
        history=icm_single_run(G, probabilities, S)
        total_active+=len(history[-1])
    return total_active/n_runs

def greedy_maximization(G, probabilities, k, n_runs=50, verbose=True):
    n_nodes=G.number_of_nodes()
    selected=[]
    remaining=list(range(n_nodes))

    for i in range(k):
        best_node=None
        best_gain=-1
        if verbose:
            print(f"  Итерация {i+1}/{k}: поиск узла...")
        current_influence=estimate_influence(G, probabilities, selected, n_runs) if selected else 0

        for idx, node in enumerate(remaining):
            influence_with_node=estimate_influence(G, probabilities, selected+[node], n_runs)
            gain=influence_with_node - current_influence

            if gain>best_gain:
                best_gain=gain
                best_node=node

            if verbose and (idx + 1) % max(1, len(remaining)//10)==0:
                print(f"    Прогресс: {idx + 1}/{len(remaining)} узлов проверено", end="\r")

        if verbose:
            print(f"    Выбран узел {best_node}, прирост: {best_gain:.2f}")

        selected.append(best_node)
        remaining.remove(best_node)

    return selected

def degree_based_selection(G, k):
    degree_dict=dict(G.degree())
    sorted_nodes=sorted(degree_dict.items(), key=lambda x: x[1], reverse=True)
    selected=[node for node, degree in sorted_nodes[:k]]

    return selected

def compare_greedy_vs_degree(G, probabilities, k, n_runs_eval=50):
    print()
    print("СРАВНЕНИЕ: ЖАДНЫЙ АЛГОРИТМ vs ВЫБОР ПО СТЕПЕНИ")

    # Жадный алгоритм
    print("\n1. Жадный алгоритм:")
    greedy_set=greedy_maximization(G, probabilities, k, n_runs=50, verbose=True)
    greedy_influence=estimate_influence(G, probabilities, greedy_set, n_runs_eval)
    print(f"\n   Выбранные узлы: {greedy_set}")
    print(f"   Ожидаемый охват: {greedy_influence:.2f} узлов")

    # Выбор по степени
    print("\n2. Выбор по степени:")
    degree_set=degree_based_selection(G, k)
    degree_influence=estimate_influence(G, probabilities, degree_set, n_runs_eval)

    # Выводим степени выбранных узлов
    print(f"   Выбранные узлы: {degree_set}")
    for node in degree_set:
        print(f"     Узел {node}: степень = {G.degree(node)}")
    print(f"   Ожидаемый охват: {degree_influence:.2f} узлов")

    # Результаты сравнения
    print()
    print("РЕЗУЛЬТАТ СРАВНЕНИЯ:")
    print(f"Жадный алгоритм:          {greedy_influence:.2f} активных узлов")
    print(f"Выбор по степени:          {degree_influence:.2f} активных узлов")

    difference=greedy_influence - degree_influence
    percent_improvement=(difference / degree_influence) * 100 if degree_influence > 0 else 0

    if difference>0:
        print(f"\nЖадный алгоритм лучше на {difference:.2f} узлов ({percent_improvement:.1f}%)")
    elif difference<0:
        print(f"\nВыбор по степени лучше на {abs(difference):.2f} узлов ({abs(percent_improvement):.1f}%)")
    else:
        print(f"\nРезультаты одинаковые")

    # Визуализация сравнения
    fig, ax=plt.subplots(figsize=(8, 6))

    strategies=['Жадный алгоритм', 'Выбор по степени']
    influences=[greedy_influence, degree_influence]
    colors=['lightblue', 'red']

    bars=ax.bar(strategies, influences, color=colors, edgecolor='black', linewidth=1.5)
    ax.set_ylabel('Ожидаемое количество активных узлов', fontsize=12)
    ax.set_xlabel('Стратегия выбора', fontsize=12)
    ax.set_title(f'Сравнение стратегий выбора {k} начальных узлов', fontsize=14)
    ax.set_ylim(0, max(influences)*1.2)

    for bar, val in zip(bars, influences):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2,
                f'{val:.0f}', ha='center', va='bottom', fontsize=11, fontweight='bold')

    ax.grid(True, alpha=0.3, axis='y')
    plt.tight_layout()

    return {
        'greedy': {'set': greedy_set, 'influence': greedy_influence},
        'degree': {'set': degree_set, 'influence': degree_influence},
        'difference': difference,
        'percent_improvement': percent_improvement
    }

print()
print("МОДЕЛИРОВАНИЕ РАСПРОСТРАНЕНИЯ ИНФОРМАЦИИ")

# 1. Создание графа
G=create_sbm_graph(n_nodes=200, n_blocks=4, p_in=0.15, p_out=0.008)

# 2. Назначение вероятностей активации
probabilities=activation_probabilities(G, base_prob=0.12, prob_variance=0.06)
avg_prob=np.mean(list(probabilities.values()))
print(f"Средняя вероятность активации на ребре: {avg_prob:.3f}")

# 3. Выбор начального множества для демонстрации
degree_dict=dict(G.degree())
top_nodes=sorted(degree_dict.items(), key=lambda x: x[1], reverse=True)[:k]
initial_set=[node for node, _ in top_nodes]
print(f"Начальное множество S0 (топ-3 по степени): {initial_set}")

# 4. Моделирование распространения
results=icm_multiple_runs(G, probabilities, initial_set, n_runs=100)
print(f"Результаты 100 прогонов:")
print(f"  Среднее финальное количество активных узлов: {results['avg_final_size']:.2f} ± {results['std_final_size']:.2f}")
print(f"  Процент охвата: {results['avg_final_size'] / G.number_of_nodes() * 100:.1f}%")

# 5. Визуализация распространения
single_history=icm_single_run(G, probabilities, initial_set)
pos=nx.spring_layout(G, seed=42, k=0.3)
fig1=visualize_steps(G, single_history)

# 6. Сравнение жадного алгоритма и выбора по степени
k=5  # Размер начального множества
comparison=compare_greedy_vs_degree(G, probabilities, k, n_runs_eval=100)

# Вывод итогов
print("ВЫВОДЫ:")
print("""1. Жадный алгоритм учитывает не только степень узла, но и то,
как информация будет распространяться дальше по сети.""")
print("""\n3. Выбор по степени - работает быстро, но не всегда")
находит наилучшее множество узлов.""")

plt.show()