# -*- coding: utf-8 -*-
"""С

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wg7iqylAQJBr-CBbVhEm1mjvdf_axWVx
"""

import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

g = np.array([[0, 1, 0, 0, 0, 0],
              [0, 0, 1, 0, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [1, 1, 0, 0, 1, 1],
              [0, 0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0, 0]])

#построение графа
G = nx.from_numpy_array(g, create_using=nx.DiGraph)

#перенумеровываем узлы с 1
G= nx.relabel_nodes(G, {0: '1', 1: '2', 2: '3', 3: '4', 4: '5', 5: '6'})

#рисуем граф
plt.figure(figsize=(7, 2))
plt.subplot(1, 2, 1)
pos = nx.circular_layout(G)
nx.draw_networkx_nodes(G, pos, node_color='green', node_size=300, alpha=0.6)
nx.draw_networkx_edges(G, pos, edge_color='black', arrows=True, arrowsize=20, connectionstyle='arc3,rad=0.1')
nx.draw_networkx_labels(G, pos, font_size=14, font_weight='bold')
plt.title("Сеть А", fontsize=10)
plt.axis('off') #уберем оси
plt.show()
print("\n")

#считаем центральность по собственному вектору
eigen_cent = nx.eigenvector_centrality(G)

total = sum(eigen_cent.values())
eigen_norm = {node: val/total for node, val in eigen_cent.items()}

#вычисляем лямду
A = g
c = np.array([eigen_norm[node] for node in sorted(G.nodes())])
Ac = A.T @ c
lamda= Ac[0] / c[0]

print("Центральность по собственному вектору")
print(f"λ = {lamda:.4f}")
for node in sorted(eigen_norm.keys()):
    print(f"с{node} = {eigen_norm[node]:.4f}")
print(f"Сумма = {sum(eigen_norm.values()):.4f}")
print("\n")

#расчет PageRank
for i in range(1, 10):
    alpha = i / 10
    pagerank = nx.pagerank(G, alpha=alpha)
    print(f"PageRank (α = {alpha}):")
    for node in sorted(pagerank.keys()):
        print(f"c{node} = {pagerank[node]:.6f}")
    print(f"Сумма = {sum(pagerank.values()):.6f}")

print("\n")
print("Итог при изменении α: с1, с5, с6 постепено убывают, с2 и с3 практически не меняются, немного растут, с4 стремительно увеличивается")
print("\n")
#Центральность Каца-Боначича
beta = 1.0    #коэффициент
for i in range(1, 6):
    alpha = i / 10
    katz = nx.katz_centrality(G, alpha=alpha, beta=beta)
    #так как он нормирует, то получаются не те значения, что и у нас, поэтому наши значения нужно прономировать чтоб сравнить
    print(f"Центральность Каца–Боначича (α = {alpha}, β = {beta}):")
    for node in sorted(katz.keys()):
        print(f"c{node} = {katz[node]:.6f}")

for i in range(51, 58):
    alpha = i / 100
    katz = nx.katz_centrality(G, alpha=alpha, beta=beta)
    #так как он нормирует, то получаются не те значения, что и у нас, поэтому наши значения нужно прономировать чтоб сравнить
    print(f"Центральность Каца–Боначича (α = {alpha}, β = {beta}):")
    for node in sorted(katz.keys()):
        print(f"c{node} = {katz[node]:.6f}")
print("\n")
print("Итог при изменении α: с1, с5, с6 постепено убывают, с2 и c4 постепенно увеличиваются, с3 постепенно падает")
print("Чтобы центральность Каца-Боначича оставалась однозначно определенной значение α не должно перобладать ∼ 0,57, иначе при подсчете выходит ошибка")